### ISSUE TITLE
TextScrollList.selectAll always throws an exception

### ISSUE THREAD

**Issue by mjmvisser** [LumaPictures/pymel#110]
#     self.listWidget.selectAll()
    #   File "/prod/tools/maya/python/pymel/core/uitypes.py", line 716, in selectAll
    #     self.selectIndexedItems(range(1, numberOfItems + 1))
    #   File "/prod/tools/maya/python/pymel/core/uitypes.py", line 706, in selectIndexedItems
    #     self.selectIndexedItem(x)
    # AttributeError: 'TextScrollList' object has no attribute 'selectIndexedItem' # 

The issue is in uitypes.py; selectIndexedItem should be setSelectIndexedItem (or aliases need to be created for the setSelect* methods).

**Comment by elrond79** [comment]
Good catch - fixed in:
https://github.com/LumaPictures/pymel/commit/bdba5b20910f0ae43409fd86eb1d9440acb905dc
