### ISSUE TITLE
Pymel variable as arguments to mel procedure

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#276]
_From [shweta....@gmail.com](https://code.google.com/u/108305293364353321323/) on April 01, 2011 17:46:41_

Describe the problem. I'm calling a MEL procedure via PyMel. I send in empty lists, expecting them to get filled in the MEL procedure. However I get back empty lists. The same is the case with variables sent as parameters that get set within the function What Version of Maya are you using? 2009 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) Linux What is the expected output? What do you see instead? Expected output [1, 2, 3]
Obtained : [] If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. Does maya.cmds exhibit the same problem? N/a. But mel.eval works fine.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=242_

**Comment by kartikg3** [comment]
Is the issue on the roadmap to be fixed? If so, I can try and get something out to address this.

**Comment by elrond79** [comment]
Probably not.  Since there's no way externally to tell which arguments might get modified, we'd have to track all lists given as inputs, create a corresponding temporary mel list variable, feed that to the mel procedure, check for changes after, and the propogate the changes back to the original passed-in python list.

All of which would be a pain, but doable... but the final kicker is that a bunch of formatting may be down in the conversion from python to mel, which may not be easy to reverse - ie, formatting of pymel objects, and flattening of lists, so that [(x1, y1, z1), (x2, y2, z2)] get converted to {x1, y1, z1, x2, y2, z2} in mel.

I'll add a note to the docs that the Mel class can't be used for such situations.

**Comment by kartikg3** [comment]
Great. That's what I thought too.
