### ISSUE TITLE
workspace getcwd() does not return project dir as intended

### ISSUE THREAD

**Issue by Kitefr** [LumaPictures/pymel#32]
Hello !

I have been using the old way to get the current project directory:
```
    import pymel.core as pm
    pm.workspace(q=True, rd=True)
```
Which works very well.
It outputs my current project directory : `/Users/username/3D/Animations/Seq02/`

But wit the new way, maybe i misunderstood how to use it...
```
    import pymel.core as pm
    pm.workspace.getcwd()
```
Which output the default Maya's directory: `/Users/username/Documents/maya/projects/`

Is it what was intended ?
Thank you.

**Comment by viktorasm** [comment]
According to https://groups.google.com/forum/#!topic/python_inside_maya/FbpFMMyedVE , you should use workspace.path() instead of workspace.cwd()

**Comment by Kitefr** [comment]
I tested it and you are right.
I should have use `pm.workspace.getPath()`

Thanks a lot for that.

**Comment by AdityaNSukarsono** [comment]
Hai @viktorasm , i tried to use `pm.workspace.getPath()` but not work.

My file is in : `D:\MyProject\Movie\EP01\SQ010\SH001\scenes`
When i try  `pm.workspace.getPath()` , the output file is : `C:/Users/aditya/Documents/maya/projects/default`

I'm using Maya 2016
