### ISSUE TITLE
PyMEL not working in Maya2013

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#342]
_From [cvanishr...@googlemail.com](https://code.google.com/u/110653988373651559929/) on October 27, 2013 04:53:06_

I am new to python scripting in Maya and recently after finding out about PyMEL I downloaded it and it was working in Maya. Then I set-up Eclipse IDE for writing scripts for Maya. First of all auto completion didn't work completely. And perhaps after that when I tried to run PyMEL script in Maya it gave some errors. And the worst part is, in the output window of Maya's script editor the errors keep displaying again and again like in an infinite loop and it is stuck. I have to close Maya otherwise that keeps going preventing me from working on anything else.

I am using Maya 2013 in Windows7 Professional -64 bit. The PyMEL version I'm using is PyMEL-1.0.3. 

I tried running the following code which is to create a simple UI Window.

import pymel.core as pm
window_name = 'Test Window'

if (pm.window(window_name, q = True, ex = True)):
    pm.deleteUI(window_name)

if (pm.windowPref(window_name, q = True, ex = True)):
    pm.windowPref(window_name, r = True)

window_object = pm.window(window_name)
window_object.show()    

It worked before but now I get errors which I cannot track since they keep flowing non stop. When I looked closely while the errors were displaying I noticed files named apicache.py,setup.py, factories.pyetc. There were few warnings about Maya plugins too. 

I tried another script with maya.cmds and that works.Its just the problem with PyMEL. I'm not sure what is the issue. Please help. Thank you. Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=309_

**Comment by chadrik** [comment]
2013 is no longer supported.
