### ISSUE TITLE
Bug in getClassification with satisfies argument

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#343]
_From [felix.ul...@gmx.de](https://code.google.com/u/102870833680846130390/) on October 29, 2013 03:25:12_

Describe the problem. When calling getClassification, since maya 2013 there is an argument "satisfies", that returns a bool, telling if the specified node type is of the specified classification string.
Using this argument leads to a TypeError, because the wrapped command 

1) Does not pipe through keyword-arguments
2) allways expects the commands return value to be a list (anyway, the error is already caused by 1) What Version of Maya are you using? 2014 SP 2 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) Linux Centos 6.2 64bit What Version of PyMEL are you using? 1.0.5 What is the expected output? What do you see instead? (see above - TypeError) If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. import pymel.core as pm
pm.getClassification('lambert', satisfies='shader') Does maya.cmds exhibit the same problem? no Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=310_

**Comment by kartikg3** [comment]
Have a fix for this in my local fork; I will cleanup my branch and send a PR.

**Comment by elrond79** [comment]
fixed thanks to the PR
