### ISSUE TITLE
particle attributes seem to be broken in Maya 2014

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#350]
_From [meeo...@gmail.com](https://code.google.com/u/110843665901358182303/) on October 12, 2014 13:14:54_

Describe the problem. Accessing per-particle attributes with:  partShape.pt[3].position always returns the same value (the value of the first particle), no matter which particle index is used. What Version of Maya are you using? 2014 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) 64bit SP2 What Version of PyMEL are you using? 201404 What is the expected output? What do you see instead? Expected:  the per-particle attribute value for the particle specified
Instead:  the per-particle attribute value for the first particle If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. partShape = particle(p=[(0,0,0), (1,2,3)])[1]
partShape.pt[1].position
\# Result: [0.0, 0.0, 0.0] # 
cmds.particle(query=True, order=1, attribute="position")
\# Result: [1.0, 2.0, 3.0] # Does maya.cmds exhibit the same problem? No - maya.cmds.particle works as it should. Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=317_

**Comment by elrond79** [comment]
_From [meeo...@gmail.com](https://code.google.com/u/110843665901358182303/) on October 12, 2014 13:15:50_

p.s. - this works as intended in 2012.  I'm not sure about other versions.

**Comment by elrond79** [comment]
_From [meeo...@gmail.com](https://code.google.com/u/110843665901358182303/) on October 12, 2014 14:59:57_

Update:  also broken in Maya 2015

**Comment by kartikg3** [comment]
self._currentFlatIndex always seemed to be returning 0 whether it was partShape.pt[0] or .pt[1] etc. Using currentItemIndex() instead in the ParticleComponent.attr()
