### ISSUE TITLE
Add isNodeReferenced to PyNodes

### ISSUE THREAD

**Issue by kartikg3** [LumaPictures/pymel#363]
It would be a great convenience if we could add an ```isNodeReferenced()``` method (probably derived from ```referenceQuery```?) as part of PyNodes.

I can get this out.

**Comment by elrond79** [comment]
There's already two different ways to get this:

DependNode.isReferenced()
(direct replacement)

DependNode.referenceFile()
(will return None if it's not referenced)

**Comment by elrond79** [comment]
Sorry I didn't see this before you made a commit!

**Comment by kartikg3** [comment]
No worries. 'tis great fun going through PyMEL and tinkering anyway.
