### ISSUE TITLE
nodetypes.NurbsSurface.closestPoint() fails with an error returned

### ISSUE THREAD

**Issue by windxu8** [LumaPictures/pymel#372]
Run script below:
###### 

import pymel.core as pm
n = pm.nurbsPlane()
s = pm.listRelatives(n[0],s=True)[0]
p = s.closestPoint([0,0,0], True, tolerance=0.001,space='world')
###### 

It will fail with such an error: TypeError: unbound method get() must be called with SafeApiPtr instance as first argument (got list instance instead)

**Comment by elrond79** [comment]
fixed in latest on github
