### ISSUE TITLE
ipymel tab autocomplete error

### ISSUE THREAD

**Issue by Lohult** [LumaPictures/pymel#373]
This has to do with ipymel.py. IPython.core.ipapi seems to have moved or changed and is no longer valid. The same goes for TryNext which is the real problem when trying to use "tab" while in ipymel. I found the temporary solution until the code gets updated is to use:

from IPython import get_ipython as ipget (instead of ipapi for the get_python function)

and

import IPython.core.error as ice (thus ice.TryNext() in the place of all other .TryNext occurrences)

This worked for me so far.

**Comment by elrond79** [comment]
Should be fixed as of https://github.com/LumaPictures/pymel/commit/3dcc920f2b05f15f45a7daf8faf16d3b588eb6d3
