### ISSUE TITLE
ply==3.3 No longer available at repo. Change to 3.4

### ISSUE THREAD

**Issue by ghost** [LumaPictures/pymel#382]
Ply 3.3 no longer exists at https://pypi.python.org/simple/ply/ This is still being referenced as of 1.0.9rc1

3.4 is the minimum version.

**Comment by elrond79** [comment]
removed the requirement from setup.py entirely, as pymel includes it's own version of ply in pymel.utils.external.ply

e3118820edc48e06e518cf64dc755eb47547758d
