### ISSUE TITLE
pymel duplicate crashes maya during redo

### ISSUE THREAD

**Issue by bensch128** [LumaPictures/pymel#391]
Hi, 
   Thanks for this awesome toolkit. I'm using it a lot for a project and its made everything easier.

However, I did run into a problem with pymel.core.general.duplicate.

I'm on Maya 2016 and using the default implementation of pymel.
I used pm.duplicate() with a couple of transforms with shapes as leaves selected.
Then I performed an undo and then redo, Maya usually crashes immediately

If duplicate() is given the list of nodes to duplicate manually, it crashes more consistently.

maya.cmds.duplicate() works correctly all of the time.

Sincerely,
Ben

**Comment by elrond79** [comment]
Hmm... can you provide a script we can use to replicate the issue?

**Comment by bensch128** [comment]
Nevermind, I can't reproduce it. 
I think that the crash was actually related to a totally different issue of using undoInfo(openContext=True) and making sure that all changes actually occur within the context. Maya's signals make this surprisingly difficult (but not Qt signals...)

**Comment by elrond79** [comment]
Ok, going to close this issue then!
