### ISSUE TITLE
Request: Method on Attributes to query default value.

### ISSUE THREAD

**Issue by ldunham1** [LumaPictures/pymel#400]
Request: Method on Attribute class to query default value.
Currently required to use;
pm.addAttr(attr, query=True, defaultValue=True)

Expected behaviour (for clarity);

class Attribute(PyNode):
    def defaultValue(self):
        """
        Returns the default value for the attribute.
        addAttr -q -dv
        """
        return cmds.addAttr(self, query=True, defaultValue=True)

**Comment by elrond79** [comment]
Closed - fixed by PR401
