### ISSUE TITLE
Maya Japanese UI issue:   except RuntimeError, e:             if str(e)

### ISSUE THREAD

**Issue by miquelcampos** [LumaPictures/pymel#402]
I am working in Japan and some of my coworkers point me to a strange error regarding the ASCII characters with Maya in Japanese

After a little research I have found that if you catch an error the str() representation have some issue with unicodeEncode

(This Example only fail with MAYA in JAPANESE)

```
import maya.cmds as cmds
cmds.spaceLocator()
cmds.spaceLocator()

    

try:
    cmds.connectAttr("locator1.translates", "locator2.translate", f=True)
except RuntimeError, e:
    print str(e)
```

This is the error log:
エラー: UnicodeEncodeError: file <maya console> line 10: ascii # 

```

import maya.cmds as cmds
cmds.spaceLocator()
cmds.spaceLocator()   

try:
    cmds.connectAttr("locator1.translates", "locator2.translate", f=True)
except RuntimeError, e:
    print repr(e)
```

This is the print of the repr
RuntimeError(u"\u30bd\u30fc\u30b9 \u30a2\u30c8\u30ea\u30d3\u30e5\u30fc\u30c8 'locator1.translates' \u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\n",)

This is affecting pymel in the code general.py module line 219

```
def connectAttr(source, destination, **kwargs):
    """

Maya Bug Fix:
  - even with the 'force' flag enabled, the command would raise an error if the connection already existed.

    """
    if kwargs.get('force', False) or kwargs.get('f', False):
        try:
            cmds.connectAttr(source, destination, **kwargs)
        except RuntimeError, e:
            if str(e) != 'Maya command error':
                # we only want to pass on a certain connection error.  all others we re-raise
                raise e
    else:
        cmds.connectAttr(source, destination, **kwargs)
```

Cheers,
Miquel

**Comment by elrond79** [comment]
This should be fixed here: 6c78a901a13d5d6d76050952500e9eb8b878be71

Thanks for the report!
