### ISSUE TITLE
ikHandle does not return pynodes

### ISSUE THREAD

**Issue by salvatimarc** [LumaPictures/pymel#410]
i found out that ikhandle command would return an array of strings when called with a name that already exists in the maya scene. This will happen only if the already existing node is not at the root.
so one can reproduce the problem by : 
creating two joint chains (joint1,joint2,joint3) and  (joint4,joint5,joint6)
execute pm.ikHandle(name="myikhandle", startJoint="joint1", endEffector="joint3")
(this last command returns array of Pynodes)
parent myikhandle to something (creating a group is enough)
execute pm.ikHandle(name="myikhandle", startJoint="joint4", endEffector="joint6")
(this last command returns array of string)

**Comment by elrond79** [comment]
fixed in:

https://github.com/LumaPictures/pymel/commit/cb5175ad1793c19311ad3f55c5d25513ec81e974

Thanks for reporting, let us know if you find any more nodes with a similar issue!
