### ISSUE TITLE
findMelOnlyCommands() broken

### ISSUE THREAD

**Issue by YKdvd** [LumaPictures/pymel#412]
[pymel.tools.mel2py.findMelOnlyCommands()](https://help.autodesk.com/cloudhelp/2018/CHS/Maya-Tech-Docs/PyMel/generated/functions/pymel.tools.mel2py/pymel.tools.mel2py.findMelOnlyCommands.html?highlight=melonly#pymel.tools.mel2py.findMelOnlyCommands) doesn't seem to work.  [mel2py imports the factories module](https://github.com/LumaPictures/pymel/blob/7213d43ba2fdad8d76e873637824f3092d1c0ea7/pymel/tools/mel2py/__init__.py#L175), and the findMelOnlyCommands() routine then [tries to call factories.mayaDocsLocation()](https://github.com/LumaPictures/pymel/blob/7213d43ba2fdad8d76e873637824f3092d1c0ea7/pymel/tools/mel2py/__init__.py#L564).  Unfortunately, "mayaDocsLocation()" is apparently [in the sibling "parsers" module](https://github.com/LumaPictures/pymel/blob/7213d43ba2fdad8d76e873637824f3092d1c0ea7/pymel/internal/parsers.py#L39), not "factories".  

Both Maya 2013 (pymel 1.0.4) and 2018 (1.0.10) seem to have the error, so it would seem this has been broken for quite some time?

If I ever get a chance I might try and fix the mayaDocsLocation() import/call, although perhaps this code relied on Maya documentation formatting that has changed/broken over the years?

**Comment by elrond79** [comment]
I removed this command, since it's not really used anywhere.  Thanks for the report!

31e27694cbca2a63eba89466ccb53bd0676cd998
