### ISSUE TITLE
Error trying to create AngleBetween node using nodetype class instance

### ISSUE THREAD

**Issue by fernoonoo** [LumaPictures/pymel#416]
When creating the angleBetween node using  nt.AngleBetween() I get the following error:

# Error: No object matches name: 1.0
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "/milk/apps/autodesk/maya/2018.3/lib/python2.7/site-packages/pymel/core/general.py", line 2341, in __new__
#     typ = cmds.nodeType(x)
#   File "/milk/apps/autodesk/maya/2018.3/lib/python2.7/site-packages/pymel/internal/pmcmds.py", line 134, in nodeType_wrapped
#     res = new_cmd(*new_args, **new_kwargs)
# RuntimeError: No object matches name: 1.0 #

**Comment by elrond79** [comment]
This should be fixed here: e4c67ea53a0b477622209608081f0abda9cdf095
