### ISSUE TITLE
Document HTML error

### ISSUE THREAD

**Issue by sevelee** [LumaPictures/pymel#420]
Hi guys, I am reading the document of pymel nodetype mesh. At the begning there is some source code showing up. I think this is a bug. Not only the "mesh node" but also all the node below "pymel.core.nodetypes". 
![image](https://user-images.githubusercontent.com/8036235/51506974-97283d80-1e29-11e9-9876-21d83b6cd531.png)

**Comment by elrond79** [comment]
Yes, that was an error in the document generation. Should be fixed in any future releases!
