### ISSUE TITLE
're' has no attribute '_pattern_type'

### ISSUE THREAD

**Issue by thirstydevil** [LumaPictures/pymel#429]
when using pm.util.path('some vlaid path').files()

This produces the following # AttributeError: module 're' has no attribute '_pattern_type' #

**Comment by pmolodo** [comment]
Fixed in https://github.com/LumaPictures/pymel/commit/146aa62b2b8dca1cde6321544ea66139145f9d08.  Thank you so much to both @tirkarthi and @thirstydevil for bringing this to my attention!
