### ISSUE TITLE
latest pymel version pu pypi.org does not include caches for Maya 2023 and Maya 2024

### ISSUE THREAD

**Issue by langlor-autodesk** [LumaPictures/pymel#464]
The official pip wheel for Pymel on pypi (https://pypi.org/project/pymel/#history) , version 1..2.0 only include caches for Maya 2022. The latest pre-release (1.3.0a2) includes caches for 2023 but not the ones for the more recent Maya 2024 version

**Comment by kattkieru** [comment]
@langlor-autodesk Where do the xml files live these days that are required to rebuild the cache?  Seems they used to be part of the docs?

**Comment by langlor-autodesk** [comment]
Hi @kattkieru , the files are now a part of the Maya2024 Windows devkit at location devkitBase/devkit/other/docs.zip

**Comment by kattkieru** [comment]
I'm on Mac.  I checked the docs for both 2023 and 2024 and neither the regular docs nor the devkit contain that folder, unless I'm missing something.  I'll grab Windows next but those files should be in each download for each system.

Is it possible for y'all to fix this?  It's bad enough that Autodesk deprecated and removed PyMEL, but making it difficult for those of us who need to support it is a bad look.  If you or one of your coworkers could generate and upload the stubs as a pull request that would be a great help to the community.

**Comment by kattkieru** [comment]
As an aside, it looks like those XML files are _not_ in the 2023.3 Windows devkit.

**Comment by chadrik** [comment]
Hi all, I just pushed 1.3.0 with support for 2023.  I'm working on an announcement for the maya-python list and a blog post which I'll post in the new few days.   We will get to work on 2024 shortly.

**Comment by dgovil** [comment]
Hey @chadrik , any word on ETAs for 2024 support? I'm starting the process of standing up 2024 right now and some dependencies use PyMel.  I figured I'd check in and see, so I can prioritize the dependencies accordingly. 

No rush (though I'm sure others would say otherwise!). I just wanted to get a sense from you about it.

**Comment by chadrik** [comment]
Done!  Let me know if you have any problems.

**Comment by dgovil** [comment]
Awesome. Thanks, Chad!
