### ISSUE TITLE
Are there type stubs for `maya.cmds` ?

### ISSUE THREAD

**Issue by Aphosis** [LumaPictures/pymel#470]
Hi,

First of all thanks for the major work on type stubs for the industry !

I was wondering if type stubs for the base `maya` package (`maya.cmds` especially) were available anywhere ? I didn't find any when installing `pymel` using `mayapy -m pip install pymel`.

I'm on `maya-2022.3` and it installed `pymel-1.4.0`.

Maybe this is not part of PyMEL, but previous versions included completions for `maya.cmds` in the devkit (in the `devkit/other/Python27/pymel/extras/completion/pyi` directory), so I was wondering if we now had the improved type stubs `pymel` ships with, but for the `maya` package.

**Comment by Aphosis** [comment]
Sorry I didn't see your reply earlier, good to hear ! Thanks a lot for all this work !

**Comment by CharlesTin0122** [comment]
https://pypi.org/project/maya-stubs/

**Comment by Aphosis** [comment]
Thanks @CharlesTin0122 ! This package had a rework recently and now does pretty much everything I wanted, we can close this.
