### ISSUE TITLE
no access to file query flags (eg: -amf) via pymel?

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#67]
_From [john.d.b...@gmail.com](https://code.google.com/u/105966220007362900071/) on April 10, 2008 09:32:58_

0.7.8, Maya 2008, CentOS-4.5

asked about this on python_inside_maya, did not receive an intelligible
answer, so I'm asking here:

is there the pymel equivalent to 'file -q -sn' or 'file -q -amf'?  I can
always use the maya.cmds.file function, but...

With the file cmd being broken up into multiple functions inside pymel.io,
it seems that there's no method for doing these types of queries that I can
find.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=34_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on April 10, 2008 12:26:57_

there's a handful of query flags, like amf, that have yet to be implemented in a
"pymel-fashion". reference queries are available through the FileReference class, and
queries on specific files are avaible on the Path class.  the rest fall into two
categories:

edits/queries on the current scene:
modified, lockFile, renameToSave, anyModified

edits/queries on options/preferences:
lastTempFile, saveDiskCache, saveTextures, prompt, options, strict

the pymel implementation of these flags will reflect these differences, perhaps by
moving the latter to the Env class.  first, i have to make sure that all of those in
the latter group are global options and not restricted to the current scene, or else
they won't make sense on the the Env class.

and remember, you can always access the original version of any command through
pymel.cmds.

**Status:** Accepted

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:40:57_

**Labels:** Milestone-Release0.7

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:01_

**Labels:** Milestone-0.7.x

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on October 29, 2009 09:01:59_

**Status:** Fixed

**Comment by hannesdelbeke** [comment]
hi it says this is fixed but no PR is linked?

**Comment by hannesdelbeke** [comment]
found pymel command: (thx Bob White)
pm.system.isModified()

https://help.autodesk.com/cloudhelp/2018/JPN/Maya-Tech-Docs/PyMel/generated/functions/pymel.core.system/pymel.core.system.isModified.html
